### ISSUE TITLE
faied on python trainMLP.py  in the get_started.sh

### ISSUE THREAD

**Issue by andyyuan78** [avisingh599/visual-qa#13]
Dumping questions, answers, questionIDs, imageIDs, and questions lengths to text files...
100% |######################################################################################################################################################################################################|
completed dumping training data
Dumping questions, answers, questionIDs, imageIDs, and questions lengths to text files...
100% |######################################################################################################################################################################################################|
completed dumping validation data
Using Theano backend.
loaded vgg features
loaded word2vec features...
Compiling model...
Compilation done...
Training started...
   128/215375 [..............................]Traceback (most recent call last):
  File "trainMLP.py", line 116, in <module>
    main()
  File "trainMLP.py", line 108, in main
    progbar.add(args.batch_size, values=[("train loss", loss)])
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 123, in add
    self.update(self.seen_so_far+n, values)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 92, in update
    avg = self.sum_values[k][0] / max(1, self.sum_values[k][1])
TypeError: unsupported operand type(s) for /: 'list' and 'int'
Using Theano backend.
Traceback (most recent call last):
  File "evaluateMLP.py", line 102, in <module>
    main()
  File "evaluateMLP.py", line 22, in main
    model.load_weights(args.weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 781, in load_weights
    for k in range(f.attrs['nb_layers']):
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/attrs.py", line 48, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5a.pyx", line 74, in h5py.h5a.open (h5py/h5a.c:2107)
KeyError: "can't open attribute (Attribute: Can't open object)"
envy@ub1404envy:~/os_prj/github/_QA/visual-qa/scripts$

**Comment by andyyuan78** [comment]
can be fix by
in trainMLP.py
108: progbar.add(args.batch_size, values=[("train loss", loss[0])])
