### ISSUE TITLE
run evaluation failed !

### ISSUE THREAD

**Issue by andyyuan78** [avisingh599/visual-qa#14]
envy@ub1404envy:~/os_prj/github/_QA/visual-qa/scripts$ python evaluateMLP.py -model ../models/mlp_num_hidden_units_1024_num_hidden_layers_3.json -weights ../models/mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_00_loss_5.10.hdf5 -results ../results/mlp_1024_3_ep0.txt
Using Theano backend.
Traceback (most recent call last):
  File "evaluateMLP.py", line 102, in <module>
    main()
  File "evaluateMLP.py", line 22, in main
    model.load_weights(args.weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 781, in load_weights
    for k in range(f.attrs['nb_layers']):
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/attrs.py", line 48, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5a.pyx", line 74, in h5py.h5a.open (h5py/h5a.c:2107)
KeyError: "can't open attribute (Attribute: Can't open object)"
envy@ub1404envy:~/os_prj/github/_QA/visual-qa/scripts$ 

envy@ub1404envy:~/os_prj/github/_QA/visual-qa/scripts$ ll ../models/
total 365152
drwxrwxr-x 2 envy envy     4096 Feb 12 05:21 ./
drwxrwxr-x 9 envy envy     4096 Feb 11 09:54 ../
-rw-rw-r-- 1 envy envy      184 Feb 11 16:27 labelencoder.pkl
-rw-rw-r-- 1 envy envy    72080 Feb 11 16:27 labelencoder.pkl_01.npy
-rw-rw-r-- 1 envy envy 38055400 Feb 11 09:54 lstm_1_num_hidden_units_lstm_512_num_hidden_units_mlp_1024_num_hidden_layers_mlp_3_epoch_070.hdf5
-rw-rw-r-- 1 envy envy     1803 Feb 11 09:54 lstm_1_num_hidden_units_lstm_512_num_hidden_units_mlp_1024_num_hidden_layers_mlp_3.json
-rw-rw-r-- 1 envy envy 30520784 Feb 11 16:35 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_00.hdf5
-rw-rw-r-- 1 envy envy      800 Feb 11 15:49 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_00_loss_5.10.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 11 17:52 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_10.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 11 19:11 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_20.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 11 20:27 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_30.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 11 21:44 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_40.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 11 23:01 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_50.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 12 00:19 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_60.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 12 01:39 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_70.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 12 02:56 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_80.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 12 04:12 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_90.hdf5
-rw-rw-r-- 1 envy envy 30520784 Feb 12 05:21 mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_99.hdf5
-rw-rw-r-- 1 envy envy     1474 Feb 11 16:27 mlp_num_hidden_units_1024_num_hidden_layers_3.json
-rw-rw-r-- 1 envy envy      123 Feb 11 09:54 README.md
envy@ub1404envy:~/os_prj/github/_QA/visual-qa/scripts$ ll ../models/mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_00_loss_5.10.hdf5
-rw-rw-r-- 1 envy envy 800 Feb 11 15:49 ../models/mlp_num_hidden_units_1024_num_hidden_layers_3_epoch_00_loss_5.10.hdf5
envy@ub1404envy:~/os_prj/github/_QA/visual-qa/scripts$

**Comment by andyyuan78** [comment]
anyone can help?

**Comment by avisingh599** [comment]
Are you using Keras 0.2 as mentioned in the README?
