### ISSUE TITLE
vgg_feats.mat empty

### ISSUE THREAD

**Issue by 1byxero** [avisingh599/visual-qa#20]
When i tried to execute trainMLP.py is got the following error
`Using Theano backend.
Traceback (most recent call last):
  File "trainMLP.py", line 116, in <module>
    main()
  File "trainMLP.py", line 47, in main
    features_struct = scipy.io.loadmat(vgg_model_path)
  File "/home/admin13/djangolearn/myenv/local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 134, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/admin13/djangolearn/myenv/local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 58, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/home/admin13/djangolearn/myenv/local/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 224, in get_matfile_version
    raise MatReadError("Mat file appears to be empty")
scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty
`

and when i checked the file "vgg_feats.mat" it was empty.
so could you please give a link of that file?

**Comment by aniemerg** [comment]
I believe I had a similar problem. What was your output from running get_started.sh?

**Comment by 1byxero** [comment]
I did not run get_started.sh,
I executed individual commands in that, and i did not get any error while executing any of the commands, but when I executed the trainMLP.py first i got an error that vgg_feats.mat is missing,
I tried searching the file over the web and found one and downloaded it, but then realized that it was empty.
